meta_product_name: "Haze"
meta_title: "Your Travel Companion - Making Group Holidays Easier!"
meta_description: "Message, organise and split expenses easily with friends"
meta_image: "hazeogimage.png" # should exist in `app/assets/images/`
